### PR TITLE
Feature/#996 on demand

### PR DESCRIPTION
**Pull request by crowesn**
Add url helper and controller for ORCID on-demand profile creation.

### CODE REVIEW

**Comment by crowesn** [comment]
We probably want to squash these commits.

**Comment by 13miciunasl** [comment]
Can we just do it on merge?

**Comment by crowesn** [comment]
Yeah!

**Comment by crowesn** [comment]
Resolves https://github.com/uclibs/scholar_uc/issues/1090
Resolves https://github.com/uclibs/scholar_uc/issues/1089
Resolves https://github.com/uclibs/scholar_uc/issues/996

**Pull request merged**
